# Generated by Django 4.2.6 on 2023-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_tipo_documento', models.CharField(max_length=10)),
                ('numero_identidad', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
                ('pertenece_colegio', models.BooleanField(default=False)),
                ('id_colegio', models.IntegerField(blank=True, null=True)),
                ('pertenece_universidad', models.BooleanField(default=False)),
                ('id_universidad', models.IntegerField(blank=True, null=True)),
                ('id_grado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes_registrados',
            },
        ),
    ]
