# Generated by Django 5.1.1 on 2024-10-13 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T002Autores',
            },
        ),
        migrations.CreateModel(
            name='CategoriaLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('otra_categoria_cual', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Libros',
                'verbose_name_plural': 'Categorías de Libros',
                'db_table': 'T003CategoriaLibros',
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colegio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion_web', models.CharField(max_length=100)),
                ('cod_departamento', models.CharField(max_length=10)),
                ('cod_municipio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'T005colegios',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T012Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Estantes',
            fields=[
                ('id_estante', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('identificacion_estante', models.CharField(blank=True, max_length=100, null=True)),
                ('identificacion_por_estante', models.CharField(max_length=100)),
                ('orden_ubicacion_estante', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
                'db_table': 'T011Estantes',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoGenero', models.CharField(max_length=10)),
                ('nombre_Genero', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Generos',
                'verbose_name_plural': 'Generos',
                'db_table': 'T009Genero',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('numero_sub_grado', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=100)),
                ('nombre_subgrado', models.CharField(max_length=100)),
                ('cod_colegio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'T006grados',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('cod_jornada', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'T007jornadas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocodigo', models.CharField(max_length=10)),
                ('nombre_codigo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'T008tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('numeroDocumento', models.CharField(max_length=50, unique=True)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('nombreFamiliar', models.CharField(max_length=100)),
                ('celularFamiliar', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=50)),
                ('crearUsuario', models.BooleanField(default=False)),
                ('crearContrasena', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuario_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'T013Usuario',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identidad', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
                ('pertenece_colegio', models.BooleanField(default=False)),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.colegio')),
                ('tipo_genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.generos')),
                ('id_grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.grado')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.tipodocumento')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'T004estudiantes_registrados',
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='cod_jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.jornada'),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('disponibleEnBiblioteca', models.BooleanField(default=True)),
                ('agno_publicacion', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado_libro', models.BooleanField(default=True)),
                ('cantidad_copias', models.IntegerField(default=1)),
                ('cantidad_inventario', models.IntegerField(default=1)),
                ('Editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.editorial')),
                ('categoriaLibro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.categorialibros')),
                ('id_Autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros_id_Autor', to='estudiantes.autor')),
                ('id_estante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.estantes')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T001Libros',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_libro', models.DateField(blank=True, null=True)),
                ('tiempo_devolucion_dias', models.IntegerField()),
                ('ya_devuelto', models.BooleanField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('observaciones_devolucion', models.TextField(blank=True, null=True)),
                ('dias_mora', models.TextField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.libro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'T010Prestamos',
            },
        ),
    ]
