# Generated by Django 4.2.6 on 2023-10-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colegio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('cod_departamento', models.CharField(max_length=10)),
                ('cod_municipio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'colegios',
            },
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_colegio',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.colegio'),
        ),
    ]
