# Generated by Django 5.0.3 on 2024-04-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('numeroDocumento', models.CharField(max_length=50)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('ocupacion', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('nombreFamiliar', models.CharField(max_length=100)),
                ('celularFamiliar', models.CharField(max_length=15)),
                ('parentesco', models.CharField(max_length=50)),
                ('crearUsuario', models.BooleanField(default=False)),
                ('crearContrasena', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'T013Usuario',
            },
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2024-04-11 05:28:38.436083+00:00'),
        ),
        migrations.AlterModelTable(
            name='categorialibros',
            table='T003CategoriaLibros',
        ),
        migrations.AlterModelTable(
            name='colegio',
            table='T005colegios',
        ),
        migrations.AlterModelTable(
            name='editorial',
            table='T012Editoriales',
        ),
        migrations.AlterModelTable(
            name='estantes',
            table='T011Estantes',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='T004estudiantes_registrados',
        ),
        migrations.AlterModelTable(
            name='generos',
            table='T009Genero',
        ),
        migrations.AlterModelTable(
            name='grado',
            table='T006grados',
        ),
        migrations.AlterModelTable(
            name='jornada',
            table='T007jornadas',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='T010Prestamos',
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='T008tipos_documento',
        ),
    ]
