# Generated by Django 5.0.3 on 2024-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_libro_estado_libro_cantidad_copias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_libro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='observaciones_devolucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
