# Generated by Django 4.2.6 on 2023-10-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_colegio_remove_estudiante_id_colegio_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colegio',
            table='T009colegios',
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='T005estudiantes_registrados',
        ),
    ]
