# Generated by Django 5.0.3 on 2024-05-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_prestamo_fecha_devolucion_libro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
