# Generated by Django 4.1.3 on 2024-07-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_prestamo_fecha_devolucion_libro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad_inventario',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoriaLibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.categorialibros'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros_id_Autor', to='estudiantes.autor'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='dias_mora',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.libro'),
        ),
    ]
