# Generated by Django 4.2.6 on 2023-10-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_colegio_table_alter_estudiante_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(max_length=100)),
                ('nombre_subgrado', models.CharField(max_length=100)),
                ('cod_jornada', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'T010grados',
            },
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id_grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.grado'),
        ),
    ]
