# Generated by Django 4.2.6 on 2023-10-26 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_grado_alter_estudiante_id_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaConClavesForaneas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.colegio')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.grado')),
            ],
            options={
                'verbose_name': 'Tabla con Claves Foraneas',
                'verbose_name_plural': 'Tablas con Claves Foraneas',
                'db_table': 'T013nombre_de_tabla_personalizada',
            },
        ),
    ]
