# Generated by Django 5.1.1 on 2024-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_libro_cantidad_inventario_alter_libro_categorialibro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
