# Generated by Django 5.1.1 on 2024-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_alter_usuario_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numeroDocumento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
