# Generated by Django 4.2.6 on 2023-10-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_tablaconclavesforaneas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_universidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion_web', models.CharField(max_length=100)),
                ('cod_departamento', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'T006universidades',
            },
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_universidad',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.universidad'),
        ),
    ]
