# Generated by Django 4.2.6 on 2023-10-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_universidad_remove_estudiante_id_universidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('cod_jornada', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'T012jornadas',
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='jornada',
            field=models.CharField(default='Mañana', max_length=10),
        ),
    ]
