# Generated by Django 5.1.1 on 2024-10-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_usuario_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='crearContrasena',
            field=models.CharField(max_length=200),
        ),
    ]
