# Generated by Django 4.2.6 on 2023-10-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_gradoscolegiosclavesforaneas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGrados',
            fields=[
                ('numero_sub_grado', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'SubGrado',
                'verbose_name_plural': 'SubGrados',
                'db_table': 'T011subgrados',
            },
        ),
    ]
