# Generated by Django 4.2.6 on 2023-10-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_subgrados'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradoSubGrado',
            fields=[
                ('id_subgrado', models.OneToOneField(db_column='numero_sub_grado', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estudiantes.subgrados')),
                ('id_grado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.grado')),
            ],
            options={
                'verbose_name': 'T014GradoSubGrado',
                'verbose_name_plural': 'T014GradoSubGrados',
                'db_table': 'T014GradoSubGrado',
            },
        ),
    ]
