# Generated by Django 4.2.6 on 2023-10-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_gradosubgrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipocodigo', models.CharField(max_length=10)),
                ('nombre_codigo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'T015tipos_documento_id',
            },
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='cod_tipo_documento',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.tipodocumento'),
        ),
    ]
