# Generated by Django 4.2.6 on 2023-10-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_tipodocumento_remove_estudiante_cod_tipo_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='codigo',
        ),
    ]
