# Generated by Django 4.2.6 on 2023-10-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_remove_tipodocumento_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoGenero', models.CharField(max_length=10)),
                ('nombre_Genero', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Generos',
                'verbose_name_plural': 'Generos',
                'db_table': 'T019Genero',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.generos'),
        ),
    ]
