# Generated by Django 4.2.6 on 2023-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_generos_estudiante_tipo_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandejaEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estante', models.CharField(max_length=100)),
                ('identificacion_por_estante', models.CharField(max_length=100)),
                ('orden_ubicacion_estante', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Bandeja Entrante',
                'verbose_name_plural': 'Bandejas Entrantes',
                'db_table': 't022Bandeja_Entrante',
            },
        ),
    ]
