# Generated by Django 4.2.6 on 2023-10-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0016_estantes_remove_bandejaentrante_id_estante_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bandejaentrante',
            table='T022Bandeja_Entrante',
        ),
        migrations.AlterModelTable(
            name='estantes',
            table='T021Estantes',
        ),
    ]
