# Generated by Django 4.2.6 on 2023-10-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0018_categorialibros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('disponibleEnBiblioteca', models.BooleanField(default=True)),
                ('categoriaLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.categorialibros')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T001Libros',
            },
        ),
    ]
