# Generated by Django 4.2.6 on 2023-10-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0020_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosAutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.libro')),
            ],
            options={
                'verbose_name': 'Libros y Autores',
                'verbose_name_plural': 'Libros y Autores',
                'db_table': 'T003Libros_Autores',
            },
        ),
    ]
