# Generated by Django 4.2.6 on 2023-10-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0021_librosautores'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='id_Autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.autor'),
        ),
    ]
