# Generated by Django 4.2.6 on 2023-10-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0023_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='dias_mora',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 19:47:38.936178+00:00'),
        ),
    ]
