# Generated by Django 4.2.6 on 2023-10-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0025_editorial_alter_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.editorial'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 20:12:47.089830+00:00'),
        ),
    ]
