# Generated by Django 4.2.6 on 2023-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0026_libro_editorial_alter_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='agno_publicacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_copiad_disponibles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_copias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 20:29:29.482771+00:00'),
        ),
    ]
