# Generated by Django 4.2.6 on 2023-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0027_libro_agno_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 20:37:30.595486+00:00'),
        ),
        migrations.AlterModelTable(
            name='editorial',
            table='T025Editoriales',
        ),
    ]
