# Generated by Django 4.2.6 on 2023-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0028_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='edad',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 20:38:21.212050+00:00'),
        ),
    ]
