# Generated by Django 4.2.6 on 2023-10-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0029_remove_autor_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estantes',
            name='identificacion_estante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 20:41:57.917351+00:00'),
        ),
    ]
