# Generated by Django 4.2.6 on 2023-10-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0031_estadoscopiaslibros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 21:03:08.884321+00:00'),
        ),
        migrations.CreateModel(
            name='CopiasLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=100)),
                ('estado_copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estadoscopiaslibros')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.libro')),
            ],
            options={
                'verbose_name': 'Copia de Libro',
                'verbose_name_plural': 'Copias de Libros',
                'db_table': 'T023CopiasLibros',
            },
        ),
    ]
