# Generated by Django 4.2.6 on 2023-10-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0032_alter_prestamo_fecha_devolucion_real_copiaslibros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 21:30:18.775131+00:00'),
        ),
    ]
