# Generated by Django 4.2.6 on 2023-10-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0034_alter_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='estantes',
            name='estante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.libro'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 21:56:18.924392+00:00'),
        ),
    ]
