# Generated by Django 4.2.6 on 2023-10-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0035_estantes_estante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estantes',
            old_name='estante',
            new_name='id_libro',
        ),
        migrations.RemoveField(
            model_name='estantes',
            name='id_Libro',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 21:56:44.704120+00:00'),
        ),
    ]
