# Generated by Django 4.2.6 on 2023-10-27 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0036_rename_estante_estantes_id_libro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estantes',
            name='id_copia_libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.copiaslibros'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 21:57:53.860086+00:00'),
        ),
    ]
