# Generated by Django 4.2.6 on 2023-10-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0038_catalogos_alter_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 22:08:46.055056+00:00'),
        ),
        migrations.CreateModel(
            name='CatalogosLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.catalogos')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.libro')),
            ],
            options={
                'verbose_name': 'Catálogo y Libro',
                'verbose_name_plural': 'Catálogos y Libros',
                'db_table': 'T028CatalogosLibros',
            },
        ),
    ]
