# Generated by Django 4.2.6 on 2023-10-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0041_alter_prestamo_fecha_devolucion_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-27 23:33:15.403195+00:00'),
        ),
        migrations.AlterModelTable(
            name='catalogoslibros',
            table='T0288CatalogosLibros',
        ),
    ]
