# Generated by Django 4.2.6 on 2023-10-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0042_alter_prestamo_fecha_devolucion_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2023-10-28 00:25:59.323628+00:00'),
        ),
        migrations.CreateModel(
            name='ProgramaAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programacion', models.CharField(max_length=10)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('id_univercidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.universidad')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'T007Programas',
            },
        ),
    ]
