# Generated by Django 4.2.6 on 2024-03-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0045_alter_prestamo_fecha_devolucion_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.TextField(default='2024-03-08 23:13:31.401678+00:00'),
        ),
    ]
